version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/myapp
    overwrite: true


permissions:
  - object: /home/ec2-user/myapp
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
