version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node dependencies"
      - npm install
  build:
    commands:
      - echo "Building Next.js"
      - npm run build

artifacts:
  files:
    - '**/*'
    - appspec.yml
    - scripts/**/*
